[package]
name = "leetcode_rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "readme_gen"
path = "src/readme_gen.rs"

[dependencies]
regex = "1.11.0"

[lints.rust]
dead_code = "allow"
unused_macros = "allow"
